#!/usr/bin/env python3
# Regenerate src/data/propFootprints.js by analysing asset image alpha.
#   python3 tools/gen_prop_footprints.py
# Trees → narrow collider box at the trunk base; rocks → box covering most of
# the opaque body. Output is in SOURCE-IMAGE pixel space (see the file header).
from PIL import Image
import glob, os, json

ALPHA = 30
TREE_DIRS = ['craftpix-net-168228-free-tree-pixel-art-asset-pack/trees',
             'Tiny Swords (Free Pack)/Tiny Swords (Free Pack)/Terrain/Resources/Wood/Trees']
ROCK_DIRS = ['assets_custom/rocks_sand', 'assets_custom/rocks_basalt', 'assets_custom/rocks_void',
             'Tiny Swords (Free Pack)/Tiny Swords (Free Pack)/Terrain/Decorations/Rocks',
             'Tiny Swords (Free Pack)/Tiny Swords (Free Pack)/Terrain/Decorations/Rocks in the Water']

# A placed sprite's footprint is measured on the FRAME the engine actually draws.
# Horizontal spritesheets (w == n*h) render one square frame at a time, so crop
# the first frame; everything else is analysed whole.
def first_frame(im):
    w, h = im.size
    if w > h and w % h == 0 and 2 <= w // h <= 24:
        return im.crop((0, 0, h, h))
    return im

def alpha_bbox(px, w, h):
    minx, miny, maxx, maxy = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            if px[x, y][3] > ALPHA:
                minx = min(minx, x); maxx = max(maxx, x)
                miny = min(miny, y); maxy = max(maxy, y)
    return (minx, miny, maxx, maxy) if maxx >= 0 else None

def trunk_box(px, w, h, bb):
    minx, miny, maxx, maxy = bb
    band = max(3, int((maxy - miny + 1) * 0.12))
    tminx, tmaxx = w, -1
    for y in range(maxy - band + 1, maxy + 1):
        for x in range(w):
            if px[x, y][3] > ALPHA:
                tminx = min(tminx, x); tmaxx = max(tmaxx, x)
    if tmaxx < 0:
        return None
    boxh = max(6, min(band, 18))
    return round((tminx + tmaxx) / 2, 1), round(maxy - boxh / 2, 1), round((tmaxx - tminx + 1) * 0.85, 1), round(boxh, 1)

def rock_box(bb):
    minx, miny, maxx, maxy = bb
    return (round((minx + maxx) / 2, 1), round((miny + maxy) / 2, 1),
            round((maxx - minx + 1) * 0.9, 1), round((maxy - miny + 1) * 0.85, 1))

def collect(dirs, kind, table):
    for d in dirs:
        for f in sorted(glob.glob(d + '/*.png')):
            im = first_frame(Image.open(f).convert('RGBA')); w, h = im.size
            px = im.load(); bb = alpha_bbox(px, w, h)
            if not bb:
                continue
            box = trunk_box(px, w, h, bb) if kind == 'tree' else rock_box(bb)
            if not box:
                continue
            cx, cy, bw, bh = box
            table[d + '/' + os.path.basename(f)] = {'cx': cx, 'cy': cy, 'w': bw, 'h': bh}

table = {}
collect(TREE_DIRS, 'tree', table)
collect(ROCK_DIRS, 'rock', table)

hdr = ['// AUTO-GENERATED by tools/gen_prop_footprints.py (image-alpha analysis).',
 '// Per-asset collision footprint for solid props, in SOURCE-IMAGE pixel space:',
 '//   cx,cy = box centre in the source image; w,h = box size (source px).',
 '// At runtime the box is mapped to the world via the sprite\'s anchor',
 '//   (offsetX/offsetY) and scale, so it tracks the rendered prop at any scale:',
 '//     worldCX = sp.x + (cx - offsetX) * scaleX',
 '//     worldCY = sp.y + (cy - offsetY) * scaleY',
 '// Trees → narrow box at the trunk base; rocks → box covering most of the body.',
 '// Keyed by `dir + \'/\' + frame`.',
 'export const PROP_FOOTPRINTS = {']
body = ['  %s: { cx: %s, cy: %s, w: %s, h: %s },' % (json.dumps(k), v['cx'], v['cy'], v['w'], v['h'])
        for k, v in sorted(table.items())]
open('src/data/propFootprints.js', 'w').write('\n'.join(hdr + body + ['};']) + '\n')
print('wrote', len(table), 'entries')
